retail_price_tracker:
  target: dev
  outputs:
    dev:
      type: postgres
      host: warehouse
      user: warehouse
      password: warehouse
      port: 5432
      dbname: retail_dw
      schema: analytics
      threads: 4
